// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETCKTEAM30.Models;

namespace NETCKTEAM30.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20181217152110_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETCKTEAM30.Models.BinhLuan", b =>
                {
                    b.Property<int>("BinhLuanID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HangHoaID");

                    b.Property<DateTime>("NgayBl");

                    b.Property<int>("NguoiDungID");

                    b.Property<string>("NoiDung");

                    b.HasKey("BinhLuanID");

                    b.HasIndex("HangHoaID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.ChiTietHd", b =>
                {
                    b.Property<int>("ChiTietHdID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<int>("HangHoaID");

                    b.Property<int>("HoaDonID");

                    b.Property<int>("SoLuong");

                    b.HasKey("ChiTietHdID");

                    b.HasIndex("HangHoaID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("chiTietHds");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.GioiTinh", b =>
                {
                    b.Property<int>("GioiTinhID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenGT");

                    b.HasKey("GioiTinhID");

                    b.ToTable("GioiTinhs");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.HangHoa", b =>
                {
                    b.Property<int>("HanghoaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<string>("Hinh");

                    b.Property<int>("LuotMua");

                    b.Property<int>("MaLoaiID");

                    b.Property<string>("MoTa");

                    b.Property<DateTime>("NgayNhap");

                    b.Property<int>("NhaCungCapID");

                    b.Property<string>("TenHh");

                    b.HasKey("HanghoaID");

                    b.HasIndex("MaLoaiID");

                    b.HasIndex("NhaCungCapID");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("HoTen");

                    b.Property<DateTime>("NgayDat");

                    b.Property<DateTime>("NgayNhan");

                    b.Property<int>("NguoiDungID");

                    b.Property<double>("PhiVanChuyen");

                    b.Property<int>("ThanhToanID");

                    b.Property<int>("TrangThaiID");

                    b.Property<int>("VanChuyenID");

                    b.HasKey("HoaDonID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("ThanhToanID");

                    b.HasIndex("TrangThaiID");

                    b.HasIndex("VanChuyenID");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.Loai", b =>
                {
                    b.Property<int>("LoaiID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai");

                    b.HasKey("LoaiID");

                    b.ToTable("Loais");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.LoaiNgDung", b =>
                {
                    b.Property<int>("LoaiNgDungID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai");

                    b.HasKey("LoaiNgDungID");

                    b.ToTable("LoaiNgDungs");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<int>("GioiTinhID");

                    b.Property<string>("Hinh");

                    b.Property<string>("HoTen");

                    b.Property<int>("LoaiNgDungID");

                    b.Property<string>("MatKhau");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("SDT");

                    b.Property<string>("TenDangNhap");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("GioiTinhID");

                    b.HasIndex("LoaiNgDungID");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.NhaCungCap", b =>
                {
                    b.Property<int>("NhaCungCapID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("MoTa");

                    b.Property<string>("SDT");

                    b.Property<string>("TenNhaCc");

                    b.HasKey("NhaCungCapID");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten");

                    b.HasKey("ThanhToanID");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.TrangThai", b =>
                {
                    b.Property<int>("TrangThaiID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTrangThai");

                    b.HasKey("TrangThaiID");

                    b.ToTable("TrangThais");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.VanChuyen", b =>
                {
                    b.Property<int>("VanChuyenID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten");

                    b.HasKey("VanChuyenID");

                    b.ToTable("VanChuyens");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.YeuThich", b =>
                {
                    b.Property<int>("YeuThichID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HangHoaID");

                    b.Property<DateTime>("NgayChon");

                    b.Property<int>("NguoiDungID");

                    b.HasKey("YeuThichID");

                    b.HasIndex("HangHoaID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("Yeutthichs");
                });

            modelBuilder.Entity("NETCKTEAM30.Models.BinhLuan", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCKTEAM30.Models.ChiTietHd", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCKTEAM30.Models.HangHoa", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.Loai", "Loai")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaLoaiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("HangHoa")
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCKTEAM30.Models.HoaDon", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("ThanhToanID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("TrangThaiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.VanChuyen", "VanChuyen")
                        .WithMany()
                        .HasForeignKey("VanChuyenID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCKTEAM30.Models.NguoiDung", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.GioiTinh", "GioiTinh")
                        .WithMany()
                        .HasForeignKey("GioiTinhID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.LoaiNgDung", "LoaiNgDung")
                        .WithMany()
                        .HasForeignKey("LoaiNgDungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCKTEAM30.Models.YeuThich", b =>
                {
                    b.HasOne("NETCKTEAM30.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCKTEAM30.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
